### ISSUE TITLE
"Failed to Create Mod Instance"

### ISSUE THREAD

**Issue by katubug** [BlueDuckYT/The-Outer-End#77]
Heavily modded instance, not currently able to do significant troubleshooting, but I figured I'd report anyway.

Outer End version: 0.3.1
Forge version: 47.2.19
Minecraft version: 1.20.1

latest.log: https://gist.github.com/katubug/22e47642136a4ee41086ee4608c54dce

Relevant lines start at 1094.

**Comment by BlueDuckYT** [comment]
I’ll look into this later

**Comment by SillyGoblin** [comment]
I'm not sure if this alone will help, but i haven't seen any mention of Team Abnormal's Blueprint 7.0.0, which I think is a requirement of the mod. I don't know what your instance is looking like but mine is currently using Forge 47.2.0 with no issues so far, switching to your Forge version does make it crash, but that is due to some other issue with my modpack which is why i can't say for certain that just adding Blueprint will work. It does work when isolated with your versions plus Blueprint.

**Comment by BlueDuckYT** [comment]
Blueprint is required, try running it with it installed

**Comment by katubug** [comment]
Thank you both! It was in fact that I was missing Blueprint. I've gotten too reliant on Curseforge adding dependencies for me, I didn't think to check.

**Comment by BlueDuckYT** [comment]
No problem! I forgot to add Blueprint as a dependency on the newer files which caused it to not uninstall, this has been fixed with release 0.3.2 though
