### ISSUE TITLE
Incompatible with Hellion's Sniffer +

### ISSUE THREAD

**Issue by LucioMagno** [BlueDuckYT/The-Outer-End#78]

**Comment by BlueDuckYT** [comment]
Do you have a log or anything that may point towards what the incompatibility is?

**Comment by LucioMagno** [comment]
[crash-2024-01-17_17.04.51-client.txt](https://github.com/BlueDuckYT/The-Outer-End/files/13968332/crash-2024-01-17_17.04.51-client.txt)

**Comment by adozenlionsroaring** [comment]
It isn’t incompatible with Hellion’s Sniffer, I’ve got the two running alongside each other at the moment. Hellion’s Sniffer mod often misleadingly shows up in these crash reports because it expects stuff to be registered and gives an error message when it doesn’t (due to another mod breaking the game)- explanation from the author:

_“It's because Forge doesn't abort startup when a mod fails to load, but freezes registries. So none of the blocks register, but it still attempts to load the game. Resulting in my mod erroring since it expects things to be registered, but it doesn't when another mod breaks.”_

In your case, it looks like the crash has occurred because you have forgotten to install Blueprint alongside Outer End.

**Comment by BlueDuckYT** [comment]
in light of adozenlionsroaring's explanation, I'm gonna close this issue
