### ISSUE TITLE
1.20.1 The outer world 1.0.6 cannot load the world

### ISSUE THREAD

**Issue by Stupidplays** [BlueDuckYT/The-Outer-End#89]
The compatibly of blueprint is fixed, but the world cannot load

**Comment by BlueDuckYT** [comment]
I’m gonna need a log and a few more details if you want a quick fix

**Comment by Stupidplays** [comment]
[2024-03-07-2.log](https://github.com/BlueDuckYT/The-Outer-End/files/14513760/2024-03-07-2.log)
[debug-2.log](https://github.com/BlueDuckYT/The-Outer-End/files/14513766/debug-2.log)

**Comment by Meowticia2** [comment]
Just came to add that I am having the same issue.  Even when starting a new world, it won't load.

**Comment by BlueDuckYT** [comment]
It seems like blueprint is the issue here, not The Outer End. Could one of you try running it with blueprint but not the outer end installed?

**Comment by xd4rkzghost01** [comment]
I got the same issue here !
Gotta try it ! Here we go !
[Crash without Blueprint](https://github.com/BlueDuckYT/The-Outer-End/files/14518611/crash-2024-03-06_23.14.59-fml.txt)
[Log without Blueprint](https://github.com/BlueDuckYT/The-Outer-End/files/14518612/latest.log)

**Comment by BlueDuckYT** [comment]
The Outer End will always crash without Blueprint, you need to install Blueprint but removr The Outer End

**Comment by xd4rkzghost01** [comment]
My bad as reading is as good as writting, sorry for long waiting
Here without OuterEnd, Also on their side, they say its form other Mod and not them. (as i understand)

[Latest Log](https://github.com/BlueDuckYT/The-Outer-End/files/14532866/latest.log)
[ForceCrash](https://github.com/BlueDuckYT/The-Outer-End/files/14532871/crash-2024-03-07_22.28.44-server.txt)

i was force to quit the game since i cannot get trought the creation world gen and the game froze.

**Comment by BlueDuckYT** [comment]
Seems like the issue is still occuring without The Outer End installed. Must be an issue on Blueprint's end

**Comment by BlueDuckYT** [comment]
Alright, I talked to Team Abnormals and the issue is not with either The Outer End or Blueprint but rather with Moog’s end cities, which uses an unsafe method that causes issues when ran with blueprint.
